import datetime as dt

# Paths
OUTPUT_PATH = "output/"
TICKERS_FILE_PATH = ""
ALPHAVANTAGE_BASE_URL = "https://www.alphavantage.co/query"

# Global Parameters
FREE_ALPHAVANTAGE_KEY = "KMMS5F3XHGRFA7CD"
DEFAULT_START_DATE = dt.date(2008, 1, 1)
TICKERS_START_DATE = "2008-01-01"
TICKERS_END_DATE = "2025-12-01"
TIMEOUT_SECONDS = 20.0
BACKOFF_SECONDS = 15.0
MAX_RETRIES = 5